/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author user
 */
public class LibrarianDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibrarianDashboard.class.getName());

    /**
     * Creates new form LibrarianDashboard
     */
    public LibrarianDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelForTitle = new javax.swing.JPanel();
        Title3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ReservationBtn = new javax.swing.JButton();
        ReturnBookBtn = new javax.swing.JButton();
        NotifyPatronsBtn = new javax.swing.JButton();
        ViewBooksBtn = new javax.swing.JButton();
        CheckiutBookBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelForTitle.setBackground(new java.awt.Color(44, 62, 80));

        Title3.setBackground(new java.awt.Color(44, 62, 80));
        Title3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("Library System");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Librarian Dashboard");

        javax.swing.GroupLayout LabelForTitleLayout = new javax.swing.GroupLayout(LabelForTitle);
        LabelForTitle.setLayout(LabelForTitleLayout);
        LabelForTitleLayout.setHorizontalGroup(
            LabelForTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelForTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LabelForTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LabelForTitleLayout.createSequentialGroup()
                        .addComponent(Title3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(516, 516, 516))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LabelForTitleLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(640, 640, 640))))
        );
        LabelForTitleLayout.setVerticalGroup(
            LabelForTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelForTitleLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Title3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        ReservationBtn.setBackground(new java.awt.Color(204, 204, 204));
        ReservationBtn.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        ReservationBtn.setText("Reservations");
        ReservationBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReservationBtn.addActionListener(this::ReservationBtnActionPerformed);

        ReturnBookBtn.setBackground(new java.awt.Color(204, 204, 204));
        ReturnBookBtn.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        ReturnBookBtn.setText("Return Book ");
        ReturnBookBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NotifyPatronsBtn.setBackground(new java.awt.Color(204, 204, 204));
        NotifyPatronsBtn.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        NotifyPatronsBtn.setText("Notify Patrons");
        NotifyPatronsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NotifyPatronsBtn.addActionListener(this::NotifyPatronsBtnActionPerformed);

        ViewBooksBtn.setBackground(new java.awt.Color(204, 204, 204));
        ViewBooksBtn.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        ViewBooksBtn.setText("View Books");
        ViewBooksBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewBooksBtn.addActionListener(this::ViewBooksBtnActionPerformed);

        CheckiutBookBtn.setBackground(new java.awt.Color(204, 204, 204));
        CheckiutBookBtn.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        CheckiutBookBtn.setText("Checkout Book ");
        CheckiutBookBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CheckiutBookBtn.addActionListener(this::CheckiutBookBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelForTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckiutBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReservationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(ReturnBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(NotifyPatronsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)))
                .addGap(387, 387, 387))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelForTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckiutBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotifyPatronsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(ViewBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckiutBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckiutBookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckiutBookBtnActionPerformed

    private void NotifyPatronsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotifyPatronsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotifyPatronsBtnActionPerformed

    private void ViewBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksBtnActionPerformed
   BookManagement booksForm = new BookManagement();
    booksForm.setVisible(true);   
     this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ViewBooksBtnActionPerformed

    private void ReservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LibrarianDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckiutBookBtn;
    private javax.swing.JPanel LabelForTitle;
    private javax.swing.JPanel LabelForTitle1;
    private javax.swing.JPanel LabelForTitle2;
    private javax.swing.JButton NotifyPatronsBtn;
    private javax.swing.JButton ReservationBtn;
    private javax.swing.JButton ReturnBookBtn;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JButton ViewBooksBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
